### ISSUE TITLE
Data refresh

### ISSUE THREAD

**Issue by jrmhaig** [ajitsing/gocd#6] opened 2018-10-17 11:09 UTC
This may be a silly question but is there a way to get the pipeline status to update? I wrote a widget for [Smashing](https://smashing.github.io/) to watch pipelines but I found that the statuses never change.

Digging around I found that in [`lib/gocd/pipeline_status/pipeline_repository.rb`](https://github.com/ajitsing/gocd/blob/322b5fc7e21d1d524c48cff7f2da42268a6174da/lib/gocd/pipeline_status/pipeline_repository.rb) it looks as though all the data is collected once at the start and then never reloaded. Is this intended?

**Comment by ajitsing** [comment] 2018-10-17 13:52
Hi @jrmhaig 

When I created this gem, I had a different use case in mind hence you see that the data is cached. But I completely agree that the Repository should always return the latest status. I will make that change soon. Thanks for reporting this issue.

**Comment by ajitsing** [comment] 2018-10-17 17:16
@jrmhaig the issue is resolved as part of [Release 1.3](https://github.com/ajitsing/gocd/releases/tag/1.3) Let me know if you still face any issue. I will close the issue after you confirm the fix.

**Comment by jrmhaig** [comment] 2018-10-18 11:05
Thanks. That is working for me now.

After getting this working I now see that it is not showing when a pipeline is running so I have created a PR (#7). I realise that this may be too simplistic a solution but it is there in case you want to merge it.

**Closed as completed** 2018-10-18 13:49 UTC
